x = int(input("First Number : "))
y = int(input("Second Number : "))
plus = x + y
minus = x - y
multiply = x * y
divide = x / y
print(x,"+",y,"=",plus)
print(x,"-",y,"=",minus)
print(x,"*",y,"=",multiply)
print(x,"/",y,"=",divide)